language: csharp
solution: Spotify.sln
mono: none
dotnet: 3.1.403
variables:
  DOTNET_CLI_TELEMETRY_OPTOUT: true
script:
- dotnet restore
- dotnet test Spotify.Tests/Spotify.Tests.csproj
install:
- nuget restore Spotify.sln
- nuget install xunit.runners -Version 2.4.0 -OutputDirectory testrunner

