language: csharp
solution: Spotify.sln
variables:
  DOTNET_CLI_TELEMETRY_OPTOUT: true
install:
  nuget restore Spotify.sln
  nuget install xunit.runners -Version 2.4.0 -OutputDirectory testrunner
script:
 - msbuild /p:Configuration=Release Spotify.sln
 - dotnet restore
