language: csharp
solution: Spotify.sln
mono: none
dotnet: 3.1.403
variables:
  DOTNET_CLI_TELEMETRY_OPTOUT: true
script:
- dotnet build
- dotnet test Spotify.Tests/Spotify.Tests.csproj
install:
- dotnet restore
deploy:
  provider: heroku
  api_key: $HEROKU_API_KEY
  app: csc480ci
