language: csharp
solution: Spotify.sln
mono: none
dotnet: 3.1.403
variables:
  DOTNET_CLI_TELEMETRY_OPTOUT: true
install:
  nuget restore Spotify.sln
  nuget install xunit.runners -Version 2.4.0 -OutputDirectory testrunner
script:
- dotnet build
- dotnet test Spotify.Tests/Spotify.Tests.csproj
